### ISSUE TITLE
bad csrf token 

### ISSUE THREAD

**Issue by djr255** [LenAnderson/SillyTavern-EverythingPlugin#1]
I tried running the plugin but got the following error:

`ForbiddenError: invalid csrf token
    at doubleCsrf (file:///Users/djr255/SillyTavern-Launcher/SillyTavern/node_modules/csrf-csrf/lib/esm/index.js:12:35)
    at file:///Users/djr255/SillyTavern-Launcher/SillyTavern/server.js:380:53
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)
ForbiddenError: invalid csrf token
    at doubleCsrf (file:///Users/djr255/SillyTavern-Launcher/SillyTavern/node_modules/csrf-csrf/lib/esm/index.js:12:35)
    at file:///Users/djr255/SillyTavern-Launcher/SillyTavern/server.js:380:53
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)
ForbiddenError: invalid csrf token
    at doubleCsrf (file:///Users/djr255/SillyTavern-Launcher/SillyTavern/node_modules/csrf-csrf/lib/esm/index.js:12:35)
    at file:///Users/djr255/SillyTavern-Launcher/SillyTavern/server.js:380:53
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)`

Tried again with plugins off, and with plugins on but STE plugin removed and they all work fine. Each time with all browser windows closed so this is not related to having more than one ST windows open.

I use an M3 MacBook Pro with Sonoma 14.6.1 (23G93)

**Comment by LenAnderson** [comment]
Neither plugin nor extension does anything particularly fancy that should cause token problems. 

Maybe a timing issue or one of the modules has to be excluded from import.. 

SillyTavern version?
Does it say which URL was attempted that resulted in the error?
Should hopefully be responded to the browser as a 403 or other 4xx error, possibly a 500. Check your browser's dev tools (console or network tab) for those to see the attempted URL and where in the script it originated.

**Comment by djr255** [comment]
hmmm, Sillytavern 1.12.7

`8000/scripts/extensions/third-party/SillyTavern-Costumes/manifest.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8000/scripts/extensions/third-party/SillyTavern-EverythingPlugin/manifest.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
VM21 jquery-3.5.1.min.js:2 Uncaught TypeError: $(...).autocomplete is not a function
    at createTagInput (tags.js:1289:10)
    at initTags (tags.js:2022:5)
    at firstLoadInit (script.js:960:5)
    at async HTMLDocument.<anonymous> (script.js:11285:5)
:8000/api/settings/save:1 
        
        
       Failed to load resource: the server responded with a status of 403 (Forbidden)
jquery-3.5.1.min.js:2 Uncaught (in promise) Object
power-user.js:2959 Uncaught TypeError: $(...).autocomplete is not a function
    at HTMLInputElement.<anonymous> (power-user.js:2959:36)
    at Function.each (jquery-3.5.1.min.js:2:2976)
    at S.fn.init.each (jquery-3.5.1.min.js:2:1454)
    at power-user.js:2958:37
    at utils.js:394:41
:8000/api/settings/save:1 
        
        
       Failed to load resource: the server responded with a status of 403 (Forbidden)
jquery-3.5.1.min.js:2 Uncaught (in promise) Object
power-user.js:2959 Uncaught TypeError: $(...).autocomplete is not a function
    at HTMLInputElement.<anonymous> (power-user.js:2959:36)
    at Function.each (jquery-3.5.1.min.js:2:2976)
    at S.fn.init.each (jquery-3.5.1.min.js:2:1454)
    at power-user.js:2958:37
    at utils.js:394:41
(anonymous) @ power-user.js:2959
each @ jquery-3.5.1.min.js:2
each @ jquery-3.5.1.min.js:2
(anonymous) @ power-user.js:2958
(anonymous) @ utils.js:394
jquery-3.5.1.min.js:2 
        
        
       POST http://127.0.0.1:8000/api/settings/save 403 (Forbidden)
send @ jquery-3.5.1.min.js:2
ajax @ jquery-3.5.1.min.js:2
saveSettings @ script.js:6716
(anonymous) @ script.js:555
(anonymous) @ utils.js:394
jquery-3.5.1.min.js:2 Uncaught (in promise) {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}'

**Comment by LenAnderson** [comment]
Costume and EverythingPlugin are server plugins, not extensions. Official ST docs have details on what that means and how to install them.

**Comment by djr255** [comment]
Ah ok. Thanks so much for taking a look and for making all this cool stuff!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by djr255** [comment]
Wanted to provide an update. I made sure to remove the improperly placed Costume and EverythingPlugin Plugins. Startup works fine with only Costume in the Plugins folder and Plugins active.  Still getting csrf errors when EverythingPlugin is active.
